<template>
  <div class="rp-paper">
    <!-- Header -->
    <div class="rp-paper__header">
      <div class="rp-paper__header-top">
        <img src="https://pub.mdpi-res.com/img/design/mdpi-pub-logo-black-small1.svg?da3a8dcae975a41c?1781518159" alt="MDPI" class="rp-paper__logo" />
        <div class="rp-paper__journal">{{ manuscript.journal }}</div>
      </div>
      <div class="rp-paper__rule" />
      <h1 class="rp-paper__title">Integrity Detection Report</h1>
      <div class="rp-paper__meta">
        <span>Manuscript: <b>{{ manuscript.id }}</b></span>
        <span>Generated: <b>{{ generatedDate }}</b></span>
        <span>Items: <b>{{ stats.total }}</b></span>
      </div>
    </div>

    <!-- Summary -->
    <ReportSummary :stats="stats" />

    <!-- Sections -->
    <div v-for="section in sections" :key="section.id" class="rp-paper__section">
      <h2 class="rp-paper__section-title">{{ section.title }}</h2>
      <ReportItemCard
        v-for="item in section.items"
        :key="item.id"
        :item="item"
      />
    </div>

    <!-- Disclaimer Footer -->
    <div class="rp-paper__footer">
      <div class="rp-paper__footer-divider" />
      <p class="rp-paper__footer-text">
        <b>Disclaimer:</b> This report is automatically generated by the SuSy detection system for editorial reference only.
        Detection results may contain false positives or negatives and should not be used as the sole basis for editorial decisions.
        Items with editor annotations reflect the handling editor's remarks and should be reviewed in context.
      </p>
      <p class="rp-paper__footer-brand">
        &copy; 1996-2026 MDPI (Basel, Switzerland) unless otherwise stated
      </p>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import ReportSummary from './ReportSummary.vue'
import ReportItemCard from './ReportItemCard.vue'

const props = defineProps({
  manuscript: { type: Object, required: true },
  sections: { type: Array, required: true },
  stats: { type: Object, required: true },
})

const generatedDate = computed(() => {
  const d = new Date()
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
})
</script>

<style scoped>
.rp-paper {
  width: 100%;
  max-width: 860px;
  background: #fff;
  border: 1px solid #d1d5db;
  padding: 40px 48px;
}

/* Header */
.rp-paper__header { text-align: center; margin-bottom: 28px; padding-bottom: 20px; border-bottom: 1px solid #d1d5db; }
.rp-paper__header-top {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  margin-bottom: 12px;
}
.rp-paper__logo { height: 24px; }
.rp-paper__journal { font-size: 13px; color: #6b7280; }

.rp-paper__rule {
  height: 2px;
  background: #0156ce;
  margin-bottom: 16px;
}

.rp-paper__title {
  font-size: 22px;
  font-weight: 700;
  color: #111827;
  margin: 0 0 10px 0;
}
.rp-paper__meta {
  display: flex;
  justify-content: center;
  gap: 20px;
  font-size: 12.5px;
  color: #6b7280;
}

/* Section */
.rp-paper__section { margin-bottom: 32px; }
.rp-paper__section-title {
  font-size: 16px;
  font-weight: 700;
  color: #111827;
  margin: 0 0 12px 0;
  padding-bottom: 6px;
  border-bottom: 1px solid #d1d5db;
}

/* Footer */
.rp-paper__footer { margin-top: 40px; }
.rp-paper__footer-divider { height: 1px; background: #d1d5db; margin-bottom: 14px; }
.rp-paper__footer-text { font-size: 11px; color: #9ca3af; line-height: 1.7; margin: 0 0 10px 0; }
.rp-paper__footer-brand { font-size: 11px; color: #9ca3af; text-align: center; margin: 0; line-height: 1.7; }
</style>
